### ISSUE TITLE
WordFormation definition talks about StemFormation in rdfs:comment

### ISSUE THREAD

**Issue by kurzum** [AKSW/MMoOn#1]
https://github.com/AKSW/MMoOn/blob/develop/core/mmoon.ttl#L1262

Use class names consistently:

rdfs:label "Word-formation"@en ;
               
               rdfs:subClassOf :MorphologicalRelationship ;
               
               rdfs:comment """Stem formation is the l

**Comment by BettinaKlimek** [comment]
revised this class for terminological consistency
